// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAnXe2ll3q3D76LCDC5jxKA7TKx7PlOeI',
    appId: '1:762942263053:web:72a6ae83178cbd23ff6a44',
    messagingSenderId: '762942263053',
    projectId: 'student-49677',
    authDomain: 'student-49677.firebaseapp.com',
    storageBucket: 'student-49677.appspot.com',
    measurementId: 'G-B0V3N3VF8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzB3pmauTGtwrvsWcRIU7ZJ7R0F2G9m5U',
    appId: '1:762942263053:android:b1b8f4277b7b23e6ff6a44',
    messagingSenderId: '762942263053',
    projectId: 'student-49677',
    storageBucket: 'student-49677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArcuJROIdxPec3qIS6EXyjXqwtFhQqlXg',
    appId: '1:762942263053:ios:9cda9e2ced85a7d0ff6a44',
    messagingSenderId: '762942263053',
    projectId: 'student-49677',
    storageBucket: 'student-49677.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArcuJROIdxPec3qIS6EXyjXqwtFhQqlXg',
    appId: '1:762942263053:ios:8710d3f19345f37eff6a44',
    messagingSenderId: '762942263053',
    projectId: 'student-49677',
    storageBucket: 'student-49677.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
